name: Custom-Action-Runs-Tests
description: 'Gets dependencies via npm and caches them'
inputs:
  testname:
    description: 'Name of test suite to run'
    required: true
    default: smoke
runs: 
    using: composite
    steps:  
    - name: Checkout
      uses: actions/checkout@v4.2.0
    - name: Install dependencies
      uses: ./.github/actions/cache
    - name: Run tests
      id: runTests
      run: npm run test