name: JamesActions
on:
  pull_request:
    types: 
      -opened
  workflow_dispatch:
  push:
    branches:
      - main
      - 'dev-*'
      - 'feature/**'
    paths-ignore:
      - '.github/workflows/**'
jobs:
    tests:
      runs-on: ubuntu-latest
      steps: 
        - name: Checkout
          uses: actions/checkout@v4.2.0
        - name: Install node
          uses: actions/setup-node@v4.0.4
          with:
            node-version: 20
        - name: Install dependencies
          run: npm ci
        - name: Run tests
          run: npm test

    build:
      needs: tests
      runs-on: ubuntu-latest
      outputs:
        script-file: ${{ steps.publish.outputs.script-file }}
      steps: 
        - name: Checkout
          uses: actions/checkout@v4.2.0        
        - name: Install dependencies
          run: npm ci
        - name: Build package
          run: npm run build
        - name: Publish file
          id: publish
          run: find dist/assets/*.js -type f -execdir echo 'script-file={}' >> $GITHUB_OUTPUT  ';'
        - name: Upload artifacts
          uses: actions/upload-artifact@v4
            with:
              name: dist-files
              path: dist
              #   |
              #  dist
              #  package.json
    deploy:
      needs: build
      runs-on: ubuntu-latest
      steps: 
        - name: Download artifacts
          uses: actions/download-artifact@v4
            with: 
              name: dist-files
        - name: Output contents
          run: ls
        - name: Deploy
          run: echo 'Deploying...' 
            