name: Matrix
on:
  workflow_dispatch:
  push:
    branches:
      - main
      - dev
    paths-ignore:
      - '.github/workflows/**'
jobs:
    build:
      continue-on-error: true
      strategy: 
        matrix: 
          node-version: [12, 18, 20]
          operating-system: [ubuntu-latest, windows-latest]
          include: 
            - node-version: 16
              operating-system: ubuntu-latest
          exclude:
            - node-version: 12
              operating-system: ubuntu-latest
            - node-version: 12
              operating-system: windows-latest

      runs-on: ${{ matrix.operating-system }}
      steps: 
        - name: Checkout
          uses: actions/checkout@v4.2.0
        - name: Install NodeJs
          uses: actions/setup-node@v4
          with:
            node-version: ${{ matrix.node-version }}
        - name: Install dependencies
          run: npm ci        
        - name: Run tests
          run: npm run test