name: Matrix
on:
  workflow_dispatch:
  push:
    branches:
      - main
      - dev
jobs:
    build:
      continue-on-error: true
      strategy: 
        matrix: 
          node-version: [16, 18, 20]
          operating-system: [ubuntu-latest, windows-latest]
      runs-on: ${{ matrix.operating-system }}
      steps: 
        - name: Checkout
          uses: actions/checkout@v4.2.0
        - name: Install NodeJs
          uses: actions/setup-node@v4
          with:
            node-version: ${{ matrix.node-version }}
        - name: Install dependencies
          run: npm ci        
        - name: Build package
          run: npm run build
        
        
            