  name: Practice
on: push
jobs:
    tests:
      runs-on: ubuntu-latest
      steps: 
        - name: Checkout
          uses: actions/checkout@v4.2.0
        - name: Install node
          uses: actions/setup-node@v4.0.4
          with:
            node-version: 20
        - name: Install dependencies
          run: npm ci
        - name: Run linting
          run: npm run lint
        - name: Run tests
          run: npm run test
        - name: Build
          run: npm run build
        - name: Deploy
          run: echo 'Deploying...'