name: Shared-Run-Tests
on: 
  workflow_call:
jobs:
  tests:
    runs-on: ubuntu-latest
    steps:
      - name: Get code
        uses: actions/checkout@v3
      - name: Install dependencies
        uses: ./.github/actions/cache
      - name: Run Tests
        run: npm run test