name: Shared-Deploy
on: 
  workflow_call:
    inputs:
      artifact-name:
        description: Name of the deploying artifact
        required: false
        default: dist
        type: string
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
     - name: Download artifacts
       uses: actions/download-artifact@v4
       with:
         name: ${{ inputs.artifact-name }}
     - name: List files
       run: ls    
     - name: Output contents
       run: echo "${{ toJSON(github.event) }}"
