name: Use-Shared
on:
  workflow_dispatch:
  push:
    branches:
      - main
      - dev
jobs:
    lint:    
      uses: ./.github/workflows/shared-lint.yml

    tests:
      runs-on: ubuntu-latest
      steps:
        - name: Checkout and Install Dependencies
          uses: ./.github/actions/cache
        - name: Run tests action
          id: runtests
          uses: ./.github/actions/runtests
          with: 
            testname: regression  
    
    build:
      needs: tests
      runs-on: ubuntu-latest
      steps: 
        - name: Checkout
          uses: actions/checkout@v4.2.0
        - name: Install dependencies
          uses: ./.github/actions/cache
        - name: Build package
          run: npm run build
        - name: Upload artifacts
          uses: actions/upload-artifact@v4
          with:
            name: dist-files
            path: dist

    deploy:
      needs: build
      uses: ./.github/workflows/shared-deploy.yml
      with:
        artifact-name: dist-files

    uploadReport:
      needs: [lint, build, deploy]
      if: failure()
      runs-on: unbuntu-latest
      steps:
        - name: Upload test report
          uses: actions/upload-artifact@v4
          with:
              name: testReport
              path: test.json
            