name: Use-Shared
on:
  workflow_dispatch:
  push:
    branches:
      - main
      - dev
jobs:
    lint:    
      uses: ./.github/workflows/shared-lint.yml

    build:
      runs-on: ubuntu-latest
      steps: 
        - name: Checkout
          uses: actions/checkout@v4.2.0
        - name: Install dependencies
          uses: ./.github/actions/cache
        - name: Build application
          uses: ./.github/actions/build

    runtests:
      needs: build
      uses: ./.github/workflows/shared-run-tests.yml     
    
    download:
      needs: runtests
      uses: ./.github/workflows/shared-deploy.yml
      with:
        artifact-name: dist-files

    uploadReport:
      needs: [lint, build, runtests, download]
      if: failure()
      runs-on: unbuntu-latest
      steps:
        - name: Upload test report
          uses: actions/upload-artifact@v4
          with:
              name: testReport
              path: test.json
            